apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: pipelinerun-1
spec:
  serviceAccountName: build-bot
  pipelineRef:
    name: example-pipeline

  resources:
  - name: repo
    resourceRef:
      name: arthurk-tekton-example

  workspaces:
  - name: myworkspace
    volumeClaimTemplate:
      spec:
        accessModes: 
        - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi
