apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: example-pipeline
spec:
  resources:
    - name: repo
      type: git
  workspaces:
    - name: myworkspace

  tasks:
    # Clone repo
    - name: clone-repo
      taskRef:
        name: clone-repo
      workspaces:
        - name: task-ws
          workspace: myworkspace
      resources:
        inputs:
          - name: repo
            resource: repo

    # Run tests
    - name: run-tests
      taskRef:
        name: run-tests
      workspaces:
        - name: task-ws
          workspace: myworkspace
      runAfter:
        - clone-repo

    # Build docker image and push to registry
    - name: build-and-push
      taskRef:
        name: build-and-push
      workspaces:
        - name: task-ws
          workspace: myworkspace
      runAfter:
        - run-tests

