apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata:
  name: daosie-tekton-examples
spec:
  type: git
  params:
    - name: url
      value: https://github.com/DaOsie/tekton-examples
    - name: revision
      value: master
