apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: clone-repo
spec:
  resources:
    inputs:
      - name: repo
        type: git
  workspaces:
    - name: task-ws
      mountPath: /workspace/repo/
  steps:
    - name: list-repo
      image: golang:1.14-alpine
      workingDir: /workspace/repo/
      script: ls -alh 
