apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: build-and-push
spec:
  workspaces:
    - name: task-ws
      mountPath: /workspace/repo
  steps:
    - name: build-and-push
      image: gcr.io/kaniko-project/executor:v0.19.0
      env:
        - name: DOCKER_CONFIG
          value: /tekton/home/.docker
      command:
        - /kaniko/executor
        - --dockerfile=Dockerfile
        - --context=/workspace/repo
        - --destination=damianosienicki/tekton-test:latest
